# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24a3dc4d6b9950a3512a09e911ea0e7b94ad8140fbed1e86a4c9235b44e5c2532ff4d6bad4acc0c3291fb675b41be2a17ebb9fc44f94051be749ec653e7e1b9

test:
  secret_key_base: 5d4bfd18f91525c425a2bde2ec4662b510522697af7886ea3324d27a653eed568adc44202f01e1f2bd71ed760a0854f5ab094d828363dabc3cb727c5605124a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
